In [20]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/GLB.Ts+dSST.csv",
    skiprows=1
)

print(df.shape)
print(df.columns.tolist())

df.head()

(147, 19)
['Year', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'J-D', 'D-N', 'DJF', 'MAM', 'JJA', 'SON']

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,J-D,D-N,DJF,MAM,JJA,SON
0,1880,-0.19,-0.25,-0.10,-0.17,-0.10,-.22,-.19,-.11,-.15,-.24,-.23,-.19,-.18,***,***,-0.12,-.17,-.21
1,1881,-0.20,-0.16,0.02,0.04,0.06,-.19,.01,-.04,-.16,-.22,-.19,-.07,-.09,-.10,-.18,0.04,-.07,-.19
2,1882,0.15,0.13,0.04,-0.16,-0.14,-.23,-.17,-.08,-.15,-.24,-.17,-.37,-.11,-.09,.07,-0.09,-.16,-.19
3,1883,-0.30,-0.37,-0.13,-0.18,-0.18,-.07,-.08,-.14,-.22,-.11,-.24,-.12,-.18,-.20,-.34,-0.16,-.10,-.19
4,1884,-0.13,-0.08,-0.37,-0.40,-0.34,-.35,-.31,-.28,-.27,-.25,-.34,-.31,-.29,-.27,-.11,-0.37,-.31,-.29

In [21]:
df.columns = df.columns.str.strip()

In [22]:
print(df.columns.tolist())

['Year', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'J-D', 'D-N', 'DJF', 'MAM', 'JJA', 'SON']

In [23]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/GLB.Ts+dSST.csv",
    skiprows=1,
    na_values="***"
)

df.columns = df.columns.str.strip()

print(df.shape)
print(df.columns.tolist())

df.head()

(147, 19)
['Year', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'J-D', 'D-N', 'DJF', 'MAM', 'JJA', 'SON']

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,J-D,D-N,DJF,MAM,JJA,SON
0,1880,-0.19,-0.25,-0.10,-0.17,-0.10,-0.22,-0.19,-0.11,-0.15,-0.24,-0.23,-0.19,-0.18,NaN,NaN,-0.12,-0.17,-0.21
1,1881,-0.20,-0.16,0.02,0.04,0.06,-0.19,0.01,-0.04,-0.16,-0.22,-0.19,-0.07,-0.09,-0.10,-0.18,0.04,-0.07,-0.19
2,1882,0.15,0.13,0.04,-0.16,-0.14,-0.23,-0.17,-0.08,-0.15,-0.24,-0.17,-0.37,-0.11,-0.09,0.07,-0.09,-0.16,-0.19
3,1883,-0.30,-0.37,-0.13,-0.18,-0.18,-0.07,-0.08,-0.14,-0.22,-0.11,-0.24,-0.12,-0.18,-0.20,-0.34,-0.16,-0.10,-0.19
4,1884,-0.13,-0.08,-0.37,-0.40,-0.34,-0.35,-0.31,-0.28,-0.27,-0.25,-0.34,-0.31,-0.29,-0.27,-0.11,-0.37,-0.31,-0.29

In [24]:
climate_df = df[['Year', 'J-D']]

In [25]:
climate_df.head()

   Year   J-D
0  1880 -0.18
1  1881 -0.09
2  1882 -0.11
3  1883 -0.18
4  1884 -0.29

In [27]:
climate_df.to_csv(
    "../data/processed/climate_trend_base.csv",
    index=False
)

In [28]:
print(df.shape)

(147, 19)

In [29]:
print(df.columns.tolist())

['Year', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'J-D', 'D-N', 'DJF', 'MAM', 'JJA', 'SON']

In [30]:
climate_df.head()

   Year   J-D
0  1880 -0.18
1  1881 -0.09
2  1882 -0.11
3  1883 -0.18
4  1884 -0.29

In [31]:
climate_df.to_csv(
    "../data/processed/climate_trend_base.csv",
    index=False
)

In [32]:
climate_df.head()

   Year   J-D
0  1880 -0.18
1  1881 -0.09
2  1882 -0.11
3  1883 -0.18
4  1884 -0.29

In [33]:
df.columns.tolist()

['Year',
 'Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'Oct',
 'Nov',
 'Dec',
 'J-D',
 'D-N',
 'DJF',
 'MAM',
 'JJA',
 'SON']

In [34]:
df.shape

(147, 19)