In [6]:
import pandas as pd
import numpy as np

In [7]:
climate_df = pd.read_csv(
    "../data/processed/climate_trend_base.csv"
)

climate_df.head()

   Year   J-D
0  1880 -0.18
1  1881 -0.09
2  1882 -0.11
3  1883 -0.18
4  1884 -0.29

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display plots inside the notebook
%matplotlib inline
#always set the above while again loading

In [10]:
# Load dataset
climate_df = pd.read_csv("../data/processed/climate_trend_base.csv")

# Display first five rows
climate_df.head()

   Year   J-D
0  1880 -0.18
1  1881 -0.09
2  1882 -0.11
3  1883 -0.18
4  1884 -0.29

In [11]:
climate_df.to_csv(
    "../data/processed/climate_trend_clean.csv",
    index=False
)

In [12]:
climate_df.shape

(147, 2)

In [13]:
climate_df.dtypes

Year      int64
J-D     float64
dtype: object

In [14]:
climate_df.isnull().sum()

Year    0
J-D     1
dtype: int64

In [15]:
missing_percentage = (
    climate_df.isnull().sum()
    / len(climate_df)
) * 100

missing_percentage

Year    0.000000
J-D     0.680272
dtype: float64

In [16]:
climate_df.duplicated().sum()

np.int64(0)

In [17]:
climate_df['Year'].duplicated().sum()

np.int64(0)

In [18]:
print(
    climate_df['Year'].min()
)

print(
    climate_df['Year'].max()
)

1880
2026

In [20]:
print(
    climate_df['J-D'].min()
)

print(
    climate_df['J-D'].max()
)

-0.49
1.28

In [21]:
climate_df.describe()

              Year         J-D
count   147.000000  146.000000
mean   1953.000000    0.082123
std      42.579338    0.401860
min    1880.000000   -0.490000
25%    1916.500000   -0.200000
50%    1953.000000   -0.030000
75%    1989.500000    0.317500
max    2026.000000    1.280000

In [22]:
climate_df.to_csv(
    "../data/processed/climate_trend_clean.csv",
    index=False
)

In [23]:
clean_df = pd.read_csv(
    "../data/processed/climate_trend_clean.csv"
)

clean_df.head()

   Year   J-D
0  1880 -0.18
1  1881 -0.09
2  1882 -0.11
3  1883 -0.18
4  1884 -0.29